# Generated by Django 5.1.1 on 2024-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=20)),
                ('imgFile', models.ImageField(upload_to='image/cart/')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('noc', models.IntegerField(blank=True, default=1, null=True)),
                ('paperType', models.CharField(default='일반지', max_length=50)),
                ('process', models.IntegerField(default=4)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('coating', models.CharField(default='코팅 없음', max_length=30)),
                ('additionalRequest', models.TextField(blank=True, null=True)),
                ('coverProcess', models.IntegerField(blank=True, null=True)),
                ('coverPaperType', models.CharField(blank=True, max_length=50)),
                ('coverCoating', models.CharField(blank=True, max_length=10)),
                ('binding', models.CharField(blank=True, max_length=15)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('shape', models.CharField(blank=True, choices=[('circle', '원'), ('quandrangle', '사각형'), ('triangle', '삼각형'), ('star', '별'), ('hart', '하트'), ('free', '자유형')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('namecard', '명함'), ('promotion', '홍보물'), ('sticker', '스티커'), ('book', '책자'), ('envelope', '봉투'), ('other', '기타')], max_length=20)),
                ('img', models.ImageField(upload_to='image/goods')),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('defaultWidth', models.IntegerField()),
                ('defaultHeight', models.IntegerField()),
                ('cover', models.BooleanField(default=False)),
                ('binding', models.BooleanField(default=False)),
                ('paperClass', models.CharField(choices=[('normal', '일반'), ('high', '고급')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('postcode', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('detailAddress', models.CharField(max_length=255)),
                ('extraAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('shippingWay', models.CharField(choices=[('선불', '선불'), ('착불', '착불'), ('방문', '방문')], max_length=20)),
                ('paymentMethod', models.CharField(choices=[('신용카드', '신용카드'), ('체크카드', '체크카드'), ('모바일 결제', '모바일 결제')], max_length=20)),
                ('cardName', models.CharField(max_length=100)),
                ('cardNumber', models.CharField(max_length=20)),
                ('expirationDate', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('파일 작업', '파일 작업'), ('시안 확인', '시안 확인'), ('인쇄 중', '인쇄 중'), ('후가공 중', '후가공 중'), ('배송 중', '배송 중'), ('배송 완료', '배송 완료'), ('취소 완료', '취소 완료')], default='파일 작업', max_length=20)),
                ('deliveryTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('namecard', '명함'), ('promotion', '홍보물'), ('sticker', '스티커'), ('book', '책자'), ('envelope', '봉투'), ('other', '기타')], max_length=20)),
                ('grade', models.CharField(choices=[('high', '고급'), ('normal', '일반')], max_length=10)),
            ],
        ),
    ]
