# Generated by Django 5.1.1 on 2024-10-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='paperClass',
            field=models.CharField(choices=[('normal', '일반'), ('high', '고급'), ('pet', 'PET')], max_length=10),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='grade',
            field=models.CharField(choices=[('high', '고급'), ('normal', '일반'), ('pet', 'PET')], max_length=10),
        ),
    ]
