# Generated by Django 5.1.1 on 2024-10-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_goods_page_alter_goods_paperclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bindingType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='paperType',
            field=models.CharField(max_length=50),
        ),
    ]
