# Generated by Django 5.1.1 on 2024-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cart_bindingtype_alter_cart_papertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedcart',
            name='cardName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderedcart',
            name='cardNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderedcart',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='orderedcart',
            name='expirationDate',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='orderedcart',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('신용카드', '신용카드'), ('체크카드', '체크카드')], max_length=20, null=True),
        ),
    ]
