# Generated by Django 5.1.1 on 2024-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderedcart_cardname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='unitQuantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
