# Generated by Django 5.1.1 on 2024-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteinquiry',
            name='status',
            field=models.CharField(default='답변대기중', max_length=20),
        ),
    ]
