# Generated by Django 5.1.1 on 2024-10-22 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_quoteinquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
