# Generated by Django 5.1.1 on 2024-10-19 17:16

import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userType', models.CharField(choices=[('기본회원', '기본회원'), ('기업회원', '기업회원'), ('외국회원', '외국회원')], max_length=30)),
                ('name', models.CharField(max_length=50, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('firstNumber', models.CharField(choices=[('010', '010'), ('011', '011'), ('016', '016'), ('017', '017'), ('019', '019')], max_length=4)),
                ('middleNumber', models.IntegerField()),
                ('lastNumber', models.IntegerField()),
                ('postcode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('detailAddress', models.CharField(max_length=20)),
                ('extraAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
